version: '3.6'

services:

  vault:
    image: hashicorp/vault-enterprise:latest
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      VAULT_LOCAL_CONFIG: |
        ui = true
        default_lease_ttl = "768h"
        storage "file" {
          path = "/vault/data"
        }
        listener "tcp" {
          address = "127.0.0.1:8200"
          tls_cert_file = "/vault/config/selfsigned.crt"
          tls_key_file = "/vault/config/selfsigned.key"
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK

